sudo: false

language: python

env:
    - CONDA="python=2.7"
    - CONDA="python=3.4"
    - CONDA="python=3.5"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --all --yes
    - conda config --add channels ioos -f
    - travis_retry conda create --yes -n TEST $CONDA --file requirements.txt
    - source activate TEST
    - travis_retry conda install --yes  --file requirements-dev.txt
    - travis_retry pip install enum34
    - travis_retry pip install check-manifest
    # GUI
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script:
    - flake8 --ignore=E501 pandas_confusion samples tests
    - nosetests tests --verbose

addons:
  apt:
    packages:
    - gfortran
    - libgfortran3